lambdaclass/rex

cli/src/cli.rs

**TLDR**
```
Get either the account's address from private key, the zero address, or a random address
Usage: ethertools-cli address [OPTIONS]
Options:
--from-private-key <FROM_PRIVATE_KEY>
The private key to derive the address from. [env: PRIVATE_KEY=]
-z, --zero
The zero address.
-r, --random
A random address.
-h, --help
Print help
```
**Examples**
```Shell
cargo run --release -- address -z
cargo run --release -- address --zero
0x0000000000000000000000000000000000000000
```
```Shell
cargo run --release -- address -r
cargo run --release -- address --random
0xacbd16ef03fdbb747e7124c23a396f7670c8f77d
```
```Shell
cargo run --release -- address --from-private-key 0xe75fae0065403d4091f3d6549c4219db69c96d9de761cfc75fe9792b6166c758
0x14eff6e0bcc07363ee55d30d0a0e86386be1ca54
```

Improve `address` cmd

---

cli/src/cli.rs
cli/src/utils.rs

Given a message and a signature, recover the signer address.

Implement `signer` cmd

---

cli/src/cli.rs
cli/src/commands/l2.rs

**`l2 chain-id`**
```Shell
Get the network's chain id.
Usage: ethertools-cli l2 chain-id [OPTIONS] [RPC_URL]
Arguments:
[RPC_URL]  [env: RPC_URL=] [default: http://localhost:1729]
Options:
-h, --hex   Display the chain id as a hex-string.
-h, --help  Print help
```
**`chain-id`**
```Shell
Get the network's chain id.
Usage: ethertools-cli chain-id [OPTIONS] [RPC_URL]
Arguments:
[RPC_URL]  [env: RPC_URL=] [default: http://localhost:8545]
Options:
-h, --hex   Display the chain id as a hex-string.
-h, --help  Print help
```

feat: `chain-id` and `l2 chain-id` cmds

---

cli/src/cli.rs
sdk/src/client/eth/mod.rs

This PR implements the `--token` flag for the `rex balance` command. To get the token balance for an address we call the contract function `balanceOf(address)` the calldata is created by the selector `0x70a08231` 16 bytes of padding, then the address of the account we are querying.
**Syntax**
```Shell
rex balance <ACCOUNT> --token <TOKEN_ADDRESS>
```

feat: rex balance --token <address>

---

cli/src/cli.rs

**Motivation**
The hash command has a duplicate declaration, and this causes runtime errors.
This removes the duplicate.

fix(cli): remove duplicate command declaration

---

cli/src/common.rs

**Motivation**
Currently the following error appears when running the `send` command.
`Found non-required positional argument with a lower index than a required positional argument: "value" index Some(2)`
Since the private key is a required parameter, it needs to be together with the positional arguments but this would interfere with providing it as an env variable.
This solves it by making the private key optional.

fix(cli): make private key optional

---

cli/README.md
cli/src/cli.rs
cli/src/common.rs
cli/src/utils.rs
sdk/src/calldata.rs
sdk/src/client/eth/mod.rs

**Motivation**
Having to manually construct calldata is annoying and inconvenient.
This implements support for basic types (fixed/ufixed, function and tuples are not implemented).
Closes #106

feat(cli): allow calling/sending using signatures

---

cli/src/cli.rs
cli/src/common.rs
cli/src/utils.rs
sdk/src/calldata.rs
sdk/src/client/eth/mod.rs

**Motivation**
Currently, the 'hex' option and the 'help' option have clashing shortenings (both begin with 'h').
This PR removes the short version of 'hex'.

fix(cli): fix chain-id arguments

---

cli/README.md
cli/src/cli.rs
cli/src/common.rs

**Motivation**
When using rex in scripts, it can be convenient to only print the address of a deployed contract.
This adds a flag to only print the address.

feat(cli): implement printing only result address in deploy

---

cli/src/cli.rs
cli/src/utils.rs

**Motivation**
There was a bug in `rex signer` implementation.
Builds the signed message payload correctly.
**How to test**
> [!IMPORTANT]
> To use `rex sign` you need #103.
```Shell
// 1. Sign a message using a private key.
rex sign 0x779172e004a01f01249038ed576516345ee9ce46a5e678b61945f33eff7448bb 0x052d7e212b30b505f337b0be5cf953c3d3175724f337b0be5cf953c3d3175724
// 2. Retrieve the signer.
rex signer 0x779172e004a01f01249038ed576516345ee9ce46a5e678b61945f33eff7448bb 0x59fa0ee54bc49b8130b465a2b378674ad70675e608407d30fe0289c800889b81167eb8e34007c5afbc845866d809583939f3a25dbae1c81ff6bf6959827b91ad1c
// 3. Check that the signer corresponds to the address associated to the private key used before.
rex address --from-private-key …
```

fix(cli): `rex signer` cmd

---

README.md
cli/src/cli.rs
cli/src/utils.rs
sdk/src/client/eth/mod.rs

**Motivation**
Expand CLI commands: implementation of the verify command
Implementation of the command verify for rex that given a message in bytes that will be passed as a hex string (with or without the 0x prefix), a signature (also a hex string) and an account's address (also a hex string), verifies if the signature was made by said account by printing true or false. 
**How to test**
To test the command you should use it like this:
```
rex verify <MESSAGE> <SIGNATURE> <ADDRESS>
```
> [!IMPORTANT]
> To use `rex sign` you need #103 and to use `rex signer` you need #107.
```Shell
// 1. Sign a message using a private key.
rex sign 0x779172e004a01f01249038ed576516345ee9ce46a5e678b61945f33eff7448bb 0x052d7e212b30b505f337b0be5cf953c3d3175724f337b0be5cf953c3d3175724
// 2. …
```

feat(cli): command verify

---

cli/src/cli.rs
cli/src/commands/l2.rs
sdk/examples/simple_usage.rs
sdk/src/client/eth/eth_sender.rs
sdk/src/sdk.rs

**Motivation**
If the output is to be used in scripts, it should not have unneeded output.
Silences the transaction wait if the print-address flag is set.
Also removes a duplicate wait on deploy.

feat(cli): make receipt wait silent if needed

---

cli/README.md
cli/src/cli.rs
sdk/src/calldata.rs

**Motivation**
It's useful to be able to decode calldata for debugging. This functionality is also useful for the ethrex CLI.
Implements calldata decoding and makes use of relevant existing tests. A decode-calldata command is impemented for ease of testing.
For symmetry, a a encode-calldata command is also implemented since the logic already exists.

feat(sdk): implement calldata decoding

---

Cargo.lock
sdk/Cargo.toml
sdk/src/errors.rs
sdk/src/keystore.rs
sdk/src/sdk.rs

Added a keystore implementation using this [crate](https://crates.io/crates/eth-keystore).
Used a default folder in the data directory when no path is provided
Closes #139

feat(sdk): add keystores support

---

cli/src/cli.rs
cli/src/commands/l2.rs
sdk/examples/simple_usage.rs
sdk/src/client/eth/errors.rs
sdk/src/client/eth/eth_sender.rs
sdk/src/client/eth/mod.rs
sdk/src/l2/withdraw.rs
sdk/src/sdk.rs

**Motivation**
`rex l2 claim-withdraw` stopped working with the latest ethrex changes.
- Fix `rex l2 claim-withdraw`
- Add amount to claim as an arg for `rex l2 claim-withdraw`.
- Update logic.
- Update the `eth_client` module with the latest ethrex changes.
- Update the `sdk/l2` module with the latest ethrex changes.

fix(cli, sdk): `rex l2 claim-withdraw`

---

sdk/src/client/eth/eth_sender.rs
sdk/src/client/eth/mod.rs
sdk/src/l2/withdraw.rs

**Motivation**
The deploy command has a `--print-address` argument, that ensures only the address of the deployed contract is printed.
In #148, a `wait_for_transaction_receipt` call was added to the sdk deploy path, which is noisy and redundant (deploy calls an optionally silent version of wait_for_transaction_receipt).
Removes the extra `wait_for_transaction_receipt` call.

fix(sdk): fix noisy deploy

---

Cargo.lock
Cargo.toml
cli/src/commands/l2.rs
sdk/src/client/eth/mod.rs
sdk/src/l2/deposit.rs
sdk/src/l2/withdraw.rs

**Motivation**
We want to add support to the ERC20 withdraws now.
* **Added `deposit_erc20` function**: Introduced a new function in `sdk/src/l2/deposit.rs` to handle ERC20 token deposits. This function constructs calldata using the `DEPOSIT_ERC20_SIGNATURE` and sends an EIP-1559 transaction to the bridge contract.
* **Updated CLI command logic**: Modified `cli/src/commands/l2.rs` to integrate ERC20 deposit handling. If a `token_address` is provided, the deposit is performed using the new `deposit_erc20` function.
Closes #154

feat(sdk): support erc20 deposits

---

cli/README.md
cli/src/cli.rs
cli/src/common.rs

**Motivation**
The current interface requires passing function signatures and arguments after a `--`. We want to remove that in order for better ux. Also in the `send` command we need to pass some hex string without flags, this is confusing.
- Remove the `last` clap config from the `send`, `call` and `encode-calldata`. This removes the necessity of the `--`.
- Add required long flags in the send command to clarify the parameters
**Examples**
- Now `call` is:
```
rex call [OPTIONS] <TO> [ARGS]
``` 
Example:
```
rex call 0xffffffffffffffffffffffffffffffffffffffff "myFunction()"
``` 
or
```
rex call 0xffffffffffffffffffffffffffffffffffffffff "myFunction2(uint256)" 42 --value 4242 --rpc-url http://localhost:8545
```
- Now `send` is:
```
rex send [OPTIONS] <TO> [ARGS]
``` …

refactor(cli): simplify rex interface

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/cli.rs
sdk/Cargo.toml
sdk/examples/simple_usage.rs
sdk/src/client/eth/eth_sender.rs
sdk/src/client/eth/mod.rs
sdk/src/l2/deposit.rs
sdk/src/l2/l1_to_l2_tx_data.rs
sdk/src/l2/withdraw.rs
sdk/src/privileged_transaction_data.rs
sdk/src/sdk.rs
sdk/tests/tests.rs

**Motivation**
`ethrex` version was outdated.
- Updates `ethrex` to the latest release `v0.0.4-alpha`.
- `ratatui` and `dialoger` use incompatible versions of `unicode-width`, and we were only importing `ethrex_l2` to use `PrivilegedTransactionData`. This PR implements its own `PrivilegedTransactionData` and removes the `ethrex_l2` dependency entirely. This implementation will be removed once we have #185.
- Replaces `BlockByNumber` with `ethrex`’s `BlockIdentifier`.
Closes None

chore(sdk,cli): bump ethrex version

---

cli/src/commands/l2.rs
sdk/src/l2/deposit.rs
sdk/tests/tests.rs

**Motivation**
We were not estimating gas when doing a deposit, leading to a loss of funds when the tx failed
- If we don't pass gas_limit as an override the ethrex-sdk will estimate the necessary gas using eth_estimateGas

feat(sdk): estimate gas when callling deposit_through_contract_call

---

cli/src/cli.rs
sdk/src/sdk.rs
sdk/tests/tests.rs

**Motivation**
In #192, our `deploy()` function was replaced by the ethrex version. The problem is that the ethrex implementation internally calls [wait_for_transaction_receipt()](https://github.com/lambdaclass/ethrex/blob/1d9fdf41e0e549db862112eb8e618eff85220f2a/crates/l2/sdk/src/sdk.rs#L86), which spams `stdout`.
Restore our `deploy()` implementation until the ethrex one can be silenced.
Closes None

fix(sdk): silent deploy
